---
- set_fact: 
    mailsystem_db_demo_seed_remote_path: /root/ansible_mailserver_demo_seed.sql

- name: Generate seed SQL statements
  template: src=mailsystem_db_demo_seed.sql.jj2
            dest={{mailsystem_db_demo_seed_remote_path}}
            mode="u=rw,g=,o="

- name: Import seed data
  shell: mysql -h {{_mailsystem_db.host}}
          --user={{_mailsystem_db.user}} --password={{_mailsystem_db.password}}
          {{mailsystem_db.db}} < {{mailsystem_db_demo_seed_remote_path}}

- name: Remove seed sql
  file: state=absent
        path={{mailsystem_db_demo_seed_remote_path}}
